name:                mtaylor-io-iam-core
version:             0.1.0.0
github:              "mtaylorio/iam-core"
license:             BSD-3-Clause
author:              "Mike Taylor"
maintainer:          "mike.charles.taylor@gmail.com"
copyright:           "Copyright (c) 2024"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mtaylor91/iam-mtaylor-io-core#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- base64 >= 0.4 && < 0.5
- bytestring >= 0.11 && < 0.12
- data-textual
- ed25519
- email-validate
- entropy
- http-types
- mtl
- network
- network-ip
- servant-server
- text >= 2.0 && < 2.1
- time
- uuid

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  iam-mtaylor-io-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iam-mtaylor-io-core
